# https://github.com/sasstools/sass-lint/tree/develop/docs/rules
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 0
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals: 1
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 2
  no-warn: 2

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2

  # Name Formats
  class-name-format: 0                  # Someday enforce (use BEM-style methodology)
  function-name-format: 1               # Someday enforce (helps readability)
  id-name-format: 0
  mixin-name-format: 1                  # Someday enforce (helps readability)
  placeholder-name-format: 1            # Someday enforce (helps readability)
  variable-name-format: 1               # Someday enforce (helps readability)

  # Style Guide
  bem-depth: 0
  border-zero: 0
  brace-style: 2
  clean-import-paths: 2
  empty-args: 0
  hex-length: 2
  hex-notation: 0
  indentation:
    - 2
    - size: 4
  leading-zero: 0
  nesting-depth: 0
  property-sort-order: 0
  quotes: 2
  shorthand-values: 1
  url-quotes: 2
  variable-for-property: 1
  zero-unit: 1
 
  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2
 
  # Final Items
  trailing-semicolon: 2
  final-newline: 0
